### ISSUE TITLE
Refactoring of tests to use tempdir

### ISSUE THREAD

**Issue by heavelock** [ROBelgium/MSNoise#100]
How about using a tempfile library to perform test? When using it, user doesn't have to take care about leftovers from tests because it gets cleaned every after executing test suite. It would make the whole package more testable.

**Comment by ThomasLecocq** [comment]
I don't remember why I didn't do that in the first place, maybe because I wanted to check the content of the test dir afterwards,... Can't tell...

> It would make the whole package more testable.

Strong statement here :)

**Comment by heavelock** [comment]
By that statement I meant that performing tests when real dir is in use needs more attention than just running them in IDE. With use of the tempdir and mockups we could achieve possibility to split the whole tests package into smaller parts. In that way you could run a small portion of tests instead of a whole package at once. Another reason to split the package is to be able to separate all the tests and make them independent. Currently, when one test fails, for example test_005, test_006 will also fail but because of wrong reason. This makes the result of test not completely dependent on the feature it is testing and adds unnecessary uncertainty to the code.

This whole package of tests is good for preparing everything for users to test it manually but not rather to perform test is routinely.

**Comment by ThomasLecocq** [comment]
The idea of the tests, originally, was to check if the worflow worked, so yes, indeed, the current behaviour is linked to that. Splitting tests for specific smaller cases is of course nice indeed.

**Comment by heavelock** [comment]
So what do you think about adding additional test packages working purely as unit tests? Do I have a green light?

**Comment by ThomasLecocq** [comment]
sure !

**Comment by ThomasLecocq** [comment]
the running of tests in a temp dir have been implemented in master now. Closing.
