### ISSUE TITLE
msnoise install SQL error: Specified key was too long

### ISSUE THREAD

**Issue by rantanplan77** [ROBelgium/MSNoise#112]
`$ msnoise install`
results in my new installation in the following error:
`pymysql.err.InternalError: (1071, 'Specified key was too long; max key length is 767 bytes')`

This can be resolved by replacing String(255) by String(191) in msnoise/msnoise_table_def.py.
Background: Looks like my new MariaDB uses utf8mb4, which uses 4 bytes per character. 191*4 < 767, whereas 255 only works for utf8. 

Should I make a pull request with this change, or is this regarded as a config error on my side? It's stupid anyway to store emojis in the filepath but you never know, like this I have the capabilities to do so 🤓

**Comment by ThomasLecocq** [comment]
I have no idea what you're talking about but it looks ok :)

**Comment by rantanplan77** [comment]
New MariaDB (=successor of MySQL) uses the utf8mb4 rather than utf8 charset. This allows you to store e.g. emojis. 
Now, when creating a new config+data availability table, msnoise asks for 255 characters for the filename and path fields. If the database is in utf8mb4, 255 character * 4 bytes / characters > 767 bytes (767 bytes seems to be some maximum for the database). Therefore I suggest to reduce this to 191 bytes to allow supporting utf8mb4. utf8mb4 can store emojis :)

**Comment by ThomasLecocq** [comment]
Ok, now I understand. Not sure it's a good idea to limit the length of paths...

**Comment by rantanplan77** [comment]
good point, I will see how I can change the charset of my installation.

**Comment by ThomasLecocq** [comment]
does this help ? 
https://github.com/gogits/gogs/issues/4894

**Comment by rantanplan77** [comment]
OK, so if anybody encounters the same problem, simply add these lines to /etc/mysql/my.cnf: 

> [mysqld]
   character-set-server=utf8
   collation-server=utf8_unicode_ci 

This way, all new databases will be created in regular UTF8 and no problems with msnoise will occur. 

Funny background fact: There was a [vote](https://github.com/WPN-XM/WPN-XM/issues/462#issuecomment-156829492) on what the new default charset should be, but only 2 people participated and they both preferred utf8mb4...

**Comment by ThomasLecocq** [comment]
@rantanplan77 could you create a PR based on master and put this somewhere in the documentation?
