### ISSUE TITLE
Installation problem (missing required packages)

### ISSUE THREAD

**Issue by NimaDolatabadi** [ROBelgium/MSNoise#115]
after installing MSNoise using `pip install msnoise` when trying to run the code I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/msnoise", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pandas' distribution was not found and is required by msnoise
How to fix this?

I also have tested the program using `msnoise test` and I'vegeot the result below and many other errors 
as well.

root@NimaDolatabadi:/home/nima/Desktop/test# msnoise test
test_001_S01installer (msnoise.test.tests.MSNoiseTests) ... ERROR
test_002_ConnectToDB (msnoise.test.tests.MSNoiseTests) ... ERROR
test_003_set_and_config (msnoise.test.tests.MSNoiseTests) ... ERROR
test_004_set_and_get_filters (msnoise.test.tests.MSNoiseTests) ... ERROR
test_005_populate_station_table (msnoise.test.tests.MSNoiseTests) ... ERROR
test_006_get_stations (msnoise.test.tests.MSNoiseTests) ... ERROR
test_007_update_stations (msnoise.test.tests.MSNoiseTests) ... ERROR
test_008_scan_archive (msnoise.test.tests.MSNoiseTests) ... ERROR
test_009_control_data_availability (msnoise.test.tests.MSNoiseTests) ... ERROR
test_010_new_jobs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_011_control_jobs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_012_reset_jobs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_012b_hack_noresample (msnoise.test.tests.MSNoiseTests) ... ERROR
test_013_s03compute_cc (msnoise.test.tests.MSNoiseTests) ... ERROR
test_014_check_done_jobs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_015_check_cc_files (msnoise.test.tests.MSNoiseTests) ... ERROR
test_016_update_config (msnoise.test.tests.MSNoiseTests) ... ERROR
test_017_reset_cc_jobs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_018_recompute_cc (msnoise.test.tests.MSNoiseTests) ... ERROR
test_019_check_SACS (msnoise.test.tests.MSNoiseTests) ... ERROR
test_020_update_config (msnoise.test.tests.MSNoiseTests) ... ERROR
test_021_reprocess_BOTH (msnoise.test.tests.MSNoiseTests) ... ERROR
test_022_check_content (msnoise.test.tests.MSNoiseTests) ... ERROR
test_023_stack (msnoise.test.tests.MSNoiseTests) ... ERROR
test_024_mwcs (msnoise.test.tests.MSNoiseTests) ... ERROR
test_025_dtt (msnoise.test.tests.MSNoiseTests) ... ERROR
test_026_build_ref_datelist (msnoise.test.tests.MSNoiseTests) ... ERROR
test_027_build_movstack_datelist (msnoise.test.tests.MSNoiseTests) ... ERROR
test_028_stretching (msnoise.test.tests.MSNoiseTests) ... ERROR
test_029_create_fake_new_files (msnoise.test.tests.MSNoiseTests) ... ERROR
test_030_instrument_response (msnoise.test.tests.MSNoiseTests) ... ERROR
test_099_S01installer (msnoise.test.tests.MSNoiseTests) ... Seems to be running on local machine, skipping MySQL test

Regards

**Comment by ThomasLecocq** [comment]
Hi,

Well, this line

> pkg_resources.DistributionNotFound: The 'pandas' distribution was not found and is required by msnoise

states that you need to install ``pandas`` as a requirement for msnoise.

It's normal that the test fail, if you don't have all required packages...

**Comment by NimaDolatabadi** [comment]
I just deleted everything and installed it with conda. I'll report other errors ins **which version** topic.
