### ISSUE TITLE
which version?

### ISSUE THREAD

**Issue by NimaDolatabadi** [ROBelgium/MSNoise#116]
I'm curious about that which version of python and anaconda I should be using to install MSNoise?
I'm using anaconda3 and modules are maded fine but I'm still facing errors. 
which one would work much better: anaconda2 or anaconda3?
Regards

**Comment by ThomasLecocq** [comment]
Hey,

definitively Python3 (so Anaconda Python 3). What errors are you facing?

Thomas

**Comment by NimaDolatabadi** [comment]
I just went through the instructions on plotting a sac waveform using this: 
[MSNoise plot](http://msnoise.org/doc/plotting.html#plotting)
I have used the `msnoise test` code to see that if everything works fine and it made a lot of data in `mseed` and `sac` format. 
I just used this code to plot only one of these data:
`msnoise -c plot ccftime YA_UV05_YA_UV06.SAC` 
and the error is:
**Usage: msnoise plot ccftime [OPTIONS] STA1 STA2**
**Error: Missing argument "sta2".**
what is the problem here?

**Comment by ThomasLecocq** [comment]
You are not calling the command line properly.

> Usage: msnoise plot ccftime [OPTIONS] STA1 STA2

example:

``msnoise plot ccftime YA.UV06 YA.UV12`` 

is the way.

**Comment by ThomasLecocq** [comment]
msnoise is not designed to plot random files, it is designed to plot its own data.

**Comment by ThomasLecocq** [comment]
I have no idea what .SG2 noise data is. You should check ``obspy`` and email the ``obspy`` mailing list with an example file. I'm closing this issue now.
