### ISSUE TITLE
Stretching hard coded parameters

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#117]
L.141-142 hard-coded parameters in stretch.py

https://github.com/ROBelgium/MSNoise/blob/fee23d270c199b5cec368c767dc8b49366e3f40e/msnoise/stretch.py#L141-L142

 should be changed to 0.03 and 601 or something similar and should be something to play with (not hard-coded)

**Comment by ThomasLecocq** [comment]
👍  for making it a ``config``urable parameter

**Comment by ThomasLecocq** [comment]
done in https://github.com/ROBelgium/MSNoise/commit/5f873682bafa50c77dec0c74b143bc4d05dc8226
