### ISSUE TITLE
plot dvv fails when only one pair is being used

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#118]
compute_dtt does not plot anything when only one pair is being used. Dirty fix is to comment lines 137-141.

https://github.com/ROBelgium/MSNoise/blob/fee23d270c199b5cec368c767dc8b49366e3f40e/msnoise/plots/dvv.py#L137-L141

Also added an argument for the components in the .csv saved (l.131)

**Comment by ThomasLecocq** [comment]
"does not plot anything", but does it exit with an error? or ? What do you mean by 
> Also added an argument for the components in the .csv saved (l.131)
where did you do that ? Did you update the ``msnoise/scripts/msnoise.py`` command line interface for this ?

**Comment by Corentin3** [comment]
>but does it exit with an error? or ?

See the error below:

![image](https://user-images.githubusercontent.com/23356210/44656324-b8ab0780-a9f8-11e8-884e-279a54527977.png)

> where did you do that ? Did you update the msnoise/scripts/msnoise.py command line interface for this ?

I did this at line 131 and I just call the script as I used tod o:
                pair1.to_csv('%s-m%i-f%i-c%s.csv'%(pair, mov_stack, filterid,comp))

>not acceptable :-) Clean fix please :)

Well it works fine ;-)

**Comment by ThomasLecocq** [comment]
>I did this at line 131 and I just call the script as I used tod o:
pair1.to_csv('%s-m%i-f%i-c%s.csv'%(pair, mov_stack, filterid,comp))

Aaaah, ok, just a naming stuff; The export CSV shouldn't actually be done 1/there 2/automatically...

**Comment by Corentin3** [comment]
With the new version it still fails. Found a dirty hack to get the right .csv but... it's dirty

**Comment by ThomasLecocq** [comment]
I was waiting for you to write the code and PR :-)

**Comment by Corentin3** [comment]
With the new download of the master version, the script disappeared... Will work on a new one then and will keep you posted
