### ISSUE TITLE
Threading the Stack procedure (at least on init)

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#12]
Adding threading support to the "stack" step would be very usefull upon initialisation, at least.

**Comment by ThomasLecocq** [comment]
No, really !!!!!!!!

**Comment by ThomasLecocq** [comment]
done!

**Comment by ashtonflinders** [comment]
Is this implemented in the current build? Supplying a "-t #threads" threw a no "-t" option error.
