### ISSUE TITLE
ZR fail (compute_cc)

### ISSUE THREAD

**Issue by ashtonflinders** [ROBelgium/MSNoise#121]
While computing ZR for one of my networks worked, it consistently failed for another network. I've been testing it on a single day for two 3 component stations. I can verify that if I set components_to_compute = 'ZZ', it will work, but if I set it to 'ZR' it will fail with a missing  "Z" data error warning.

I believe this is related to (but may be wrong);

```
        comps = []
        for comp in params.components_to_compute:
            if comp[0] in ["R", "T"] or comp[1] in ["R", "T"]:
                comps.append("E")
                comps.append("N")
            else:
                comps.append(comp[0])
                comps.append(comp[1])
        comps = np.unique(comps)
```
It looks like if components_to_compute = 'ZR', the 'Z' channel will never get appended to comps (or any of the similar, RZ, TR, RT)? I think this worked for my other network because I had  components_to_compute = 'ZZ,ZR,ZT', so it forced Z to come along for the ride.

This would be my suggestion to fix;
```
        comps = []
        comps_RT = [(c[0],c[1]) for c in params.components_to_compute]
        comps_RT = np.unique(comps_RT)
        for c in comps_RT:
            if c in ["R", "T"]:
                comps.append("E")
                comps.append("N")
            else:
                comps.append(c)
        comps = np.unique(comps)
```
If anyone has something elegant, I'd be curious! I found it difficult to make this short without using regex.

-ashton

**Comment by ThomasLecocq** [comment]
solved with https://github.com/ROBelgium/MSNoise/commit/24415da5e7bd46afb7fdfdcb7b2b9b72b267d00e
