### ISSUE TITLE
Improve common error handling

### ISSUE THREAD

**Issue by XavierBeguin** [ROBelgium/MSNoise#128]
The code handling a missing `db.ini` file calls `sys.exit()` and `scripts/msnoise.py` catches all exceptions using a broad `except:` clause while trying to get the list of configured plugins.  This is an issue as it would hide any other exception and could make spotting bugs harder.

An other error-related problem is that MSNoise outputs a long traceback chain when it cannot connect to the database.  It would be nice to display a single error message to the user to make the database connection error more explicit.

**Comment by ThomasLecocq** [comment]
reolved in #135
