### ISSUE TITLE
Click version 7.0 changes command names and breaks documentation generation 

### ISSUE THREAD

**Issue by XavierBeguin** [ROBelgium/MSNoise#131]
Version 7.0 of click introduced a change in the way the python module names commands defined by a python function (see [click changelog for version 7.0](https://click.palletsprojects.com/en/7.x/changelog/#version-7-0) ):

- `Subcommands that are named by the function now automatically have the underscore replaced with a dash. If you register a function named my_command it becomes my-command in the command line interface.`

MSNoise commands like `scan_archive` are therefore renamed `scan-archive`, etc.

This not only changes the way msnoise should be used, but also breaks the generation of the documentation. Below is the error message produced by the code in the current master branch:
```python
doc$ make html
sphinx-build -b html -d .build/doctrees   . .build/html
Running Sphinx v1.8.2
No db.ini file in this directory, please run 'msnoise db init' in this folder to initialize it as an MSNoise project folder.

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/xavier/.virtualenvs/msnoise-dev/lib/python3.5/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/xavier/.virtualenvs/msnoise-dev/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/xavier/Documents/Infra/Msnoise/devel/msnoise.gitlab/doc/conf.py", line 125, in <module>
    c = click.Context(command=eval('M.%s'%command))
  File "<string>", line 1, in <module>
AttributeError: module 'msnoise.scripts.msnoise' has no attribute 'compute'

Makefile:45: recipe for target 'html' failed
make: *** [html] Error 2
```

This change of behaviour probably also introduces other undesired changes.

**Comment by ThomasLecocq** [comment]
and I think the name of the commands should remain the same in the console...
