### ISSUE TITLE
Trailing blanks in configuration values cause errors

### ISSUE THREAD

**Issue by XavierBeguin** [ROBelgium/MSNoise#137]
Adding an invisible trailing blank at the end of a configuration parameter in the admin form can cause errors that can be hard to spot.

How to reproduce:

- add a trailing blank to  `data_folder`
- run `msnoise scan_archive`
- get the error `Cannot find directory '/srv/archives/SEISMIC_DATA/MSEED '. Aborting.`

**Comment by XavierBeguin** [comment]
Sorry about these multiple commits appearing here, it's the result me deleting and re-creating of a branch on my fork after I realised I had to do some more corrections or rebasing.
(These commit are not reachable any more but still show up here. Strange.)

**Comment by ThomasLecocq** [comment]
resolved in #138
