### ISSUE TITLE
Need to update default end date values past 2019-01-01

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#147]
We should update the end date, ref end, etc....

Enddate should be changed to 2020-01-01 instead of 2019-01-01 for example.

**Comment by ThomasLecocq** [comment]
euh ? elaborate please?

**Comment by ThomasLecocq** [comment]
resolved in https://github.com/ROBelgium/MSNoise/commit/70c19dd349ebf0ad807c8c0d9e01738fd41cfdea
