### ISSUE TITLE
New_jobs & other commands lack "logging"

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#148]
When I run the 'msnoise new_jobs', no message gets written afterwards. 

msnoise new_jobs 

does not return anything anymore. Before the number of jobs added was written (at least).

Hence you need to open the admin to make sure it actually worked. Not sure it's ideal.

**Comment by ThomasLecocq** [comment]
hummm... indeed, strange.

**Comment by ThomasLecocq** [comment]
I label it as "bug" because even passing ``-vvvv`` to the command doesn't enable the ``logging.DEBUG`` level.

**Comment by ThomasLecocq** [comment]
should be resolved with https://github.com/ROBelgium/MSNoise/commit/c5691e301935b843a6ce26d669b82846b287da25 , @Corentin3 please update your master branch and check if it's ok.

**Comment by ThomasLecocq** [comment]
modified the logger to use ``logbook`` (and adding the dependency), not super sure of how I implemented it, but at least it logs for all codes + parallel threads.
