### ISSUE TITLE
Jobs-two distinct runs: How can we work with two distinct runs efficiently?

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#149]
Ok I could not find a better description for this issue.

Imagine you want to work with the full archive. You run everything smoothly (Run 1). Then you just want to compute the dv/v say for autocorrelations (Run 2). You reset the DA then create the jobs, compute the autocorrelations and stack once. BUT then comes an issue. You need to reset the STACK jobs. But it will then reset them all: from Run 1 + Run 2.

Typically, I delete all the jobs from Run 1 and re-start everything for Run 2

**Comment by ThomasLecocq** [comment]
Based on your example, when running the CC, you'll create only the STACK jobs that are linked to the autocorrelations, not the others. Why do you need to reset the STACK jobs ?

**Comment by Corentin3** [comment]
To compute the reference for example when you're done with the -m stacks

**Comment by ThomasLecocq** [comment]
I see. In the meantime, just do the REF stack first (it doesn't mark the STACK jobs Done)

**Comment by Corentin3** [comment]
Excellent! I actually just realised this and had to create the MWCS manually using this command:
_insert into jobs (day, pair, jobtype, flag) select day, pair, "MWCS", "T" from jobs where jobtype="CC" and flag="D"_

**Comment by ThomasLecocq** [comment]
that is the same as
``msnoise new_jobs --hpc CC:MWCS``

but not advised, as all STACKs might not have been calculated...

**Comment by Corentin3** [comment]
Sure it's rather a trick.
