### ISSUE TITLE
1176, "Key 'da_index' doesn't exist in table 'data_availability'"

### ISSUE THREAD

**Issue by echavess** [ROBelgium/MSNoise#151]
Hi Folks! I hope everything is going well.  I am back using Msnoise! 

After successfully populating my table, I am trying to scan the data using 
>> msnoise -t 2 scan-archive. 

My data looks like this (BUD format)
>> ls Data/OV/*

Data/OV/CPAN:
CPAN.OV.00.HHZ.2019.001
...

Data/OV/HAYA:
HAYA.OV.00.HHZ.2019.001
...

Data/OV/VIRE:
VIRE.OV.00.HHZ.2019.001
...

However, I am getting this debug error with all my miniseed files:

`2019-03-18 16:00:48 [DEBUG] ERROR: (pymysql.err.InternalError) (1176, "Key 'da_index' doesn't exist in table 'data_availability'") [SQL: 'SELECT data_availability.ref AS data_availability_ref, data_availability.net AS data_availability_net, data_availability.sta AS data_availability_sta, data_availability.comp AS data_availability_comp, data_availability.path AS data_availability_path, data_availability.file AS data_availability_file, data_availability.starttime AS data_availability_starttime, data_availability.endtime AS data_availability_endtime, data_availability.data_duration AS data_availability_data_duration, data_availability.gaps_duration AS data_availability_gaps_duration, data_availability.samplerate AS data_availability_samplerate, data_availability.flag AS data_availability_flag \nFROM data_availability USE INDEX (da_index) \nWHERE data_availability.path = %(path_1)s AND data_availability.file = %(file_1)s AND data_availability.net = %(net_1)s AND data_availability.sta = %(sta_1)s AND data_availability.comp = %(comp_1)s \n LIMIT %(param_1)s'] [parameters: {'path_1': '/Volumes/SMOMENT/Noise_analysis/Irazu/Data/OV/HAYA', 'file_1': 'HAYA.OV.00.HHZ.2019.033', 'net_1': 'OV', 'sta_1': 'HAYA', 'comp_1': 'HHZ', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/2j85)`

and finally 0 data was added: 

```
2019-03-18 16:00:55 [INFO] /Volumes/SMOMENT/Noise_analysis/Irazu/Data/OV/CPAN: Added 0 | Modified 0 | Unchanged 0
2019-03-18 16:00:55 [INFO] *** Finished: Scan Archive ***
2019-03-18 16:00:55 [INFO] It took 28.76 seconds
```

The error seems to be related to the "da_index" in mysql tables. But don't know why!
Have you all seen this before? I will appreciate all your help. 

Cheers, 

-Esteban

**Comment by ThomasLecocq** [comment]
Hey!

msnoise db upgrade

Should work ! (Except if you have duplicate entries in your db)

**Comment by echavess** [comment]
Thanks @ThomasLecocq that worked. I computed CCs fine. After that, I tried the stacking using:
msnoise stack -r -m -i 1 and got this error:

`sqlalchemy.exc.InternalError: (pymysql.err.InternalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'irazu_deslizamiento.jobs.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") [SQL: 'SELECT jobs.ref AS jobs_ref, jobs.day AS jobs_day, jobs.pair AS jobs_pair, jobs.jobtype AS jobs_jobtype, jobs.flag AS jobs_flag, jobs.lastmod AS jobs_lastmod \nFROM jobs \nWHERE jobs.pair = %(pair_1)s AND jobs.day >= %(day_1)s AND jobs.day <= %(day_2)s AND jobs.jobtype = %(jobtype_1)s AND jobs.lastmod >= %(lastmod_1)s GROUP BY jobs.day ORDER BY jobs.day'] [parameters: {'pair_1': 'OV.CPAN:OV.HAYA', 'day_1': datetime.date(2019, 1, 1), 'day_2': datetime.date(2019, 3, 3), 'jobtype_1': 'CC', 'lastmod_1': datetime.datetime(2019, 3, 18, 18, 8, 32, 953310)}] (Background on this error at: http://sqlalche.me/e/2j85)`

Do you see what's the problem? 

Thanks

**Comment by ThomasLecocq** [comment]
It's the "group by" stuff that changed in "recent" version of MySQL, you'll have to adapt your MySQL/MariaDB config (my.cnf or else), see: http://msnoise.org/doc/master/installation.html#mysql-mariadb-configuration

**Comment by ThomasLecocq** [comment]
also note, if you use the master version, do the ref stack, then reset STACK jobs, then do the mov stack, they are no longer doable in one command (and the CLI should prevent it, btw)
