### ISSUE TITLE
Only AC-SC?

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#153]
It's more a brainstorming perhaps than something to include in the future release, perhaps. But it would be useful to allow to compute single station CC only for a set of stations used.

**Comment by ThomasLecocq** [comment]
what happens if you leave the ``components_to_compute`` blank and ``components_to_compute_single_station`` with some values like ``ZZ,ZE,ZN,EN`` and then run ``new_jobs`` ?

**Comment by ThomasLecocq** [comment]
@Corentin3 could you confirm this works now with the ``msnoise compute_cc`` ?

Remember that if you changed ``components_to_compute_single_station`` *after* you defined the jobs, you need to redo ``msnoise reset DA; msnoise new_jobs``

**Comment by Corentin3** [comment]
@ThomasLecocq I confirm it works fine now
