### ISSUE TITLE
glitch in s06compute_dtt.py / (1.5.1)

### ISSUE THREAD

**Issue by filefolder** [ROBelgium/MSNoise#154]
running compute-dtt (all the steps preceding this work fine), 

unless i'm doing something wrong it looks like the script tries to delete "cohindex" before it gets created. if i remove that var from the del command it also triggers errindex, dtindex, etc

``
$ msnoise compute-dtt
2019-04-03 12:53:01 [INFO] *** Starting: Compute DT/T ***
2019-04-03 12:53:01 [DEBUG] Found 215 updated days
2019-04-03 12:53:01 [INFO] Loading mov=5 days for filter=01
2019-04-03 12:53:01 [DEBUG] Processing 2016-06-01 - 01 - 05 mov
Traceback (most recent call last):
  File "/usr/local/bin/msnoise", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/msnoise/scripts/msnoise.py", line 717, in run
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/Click-7.0-py2.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/msnoise/scripts/msnoise.py", line 414, in compute_dtt
    main(interval)
  File "/usr/local/lib/python2.7/dist-packages/msnoise/s06compute_dtt.py", line 282, in main
    cohindex,errindex, dtindex, wavg, wstd
UnboundLocalError: local variable 'cohindex' referenced before assignment

``
i'm pretty sure this is version 1.5.1.

relevant part of s06compute_dtt.py:

```
                        if len(pairArray) != 1:
                            # first stack all pairs to a ALL mean pair, using
                            # indexes of selected values:
                            new_dtArray = np.zeros(len(tArray))
                            new_errArray = np.zeros(len(tArray)) + 9999
                            new_cohArray = np.zeros(len(tArray))
                            for i in range(len(tArray)):
                                #~ if i in tindex:
                                if 1:
                                    cohindex = np.where(
                                        cohArray[:, i] >= minCoh)[0]
                                    errindex = np.where(
                                        errArray[:, i] <= maxErr)[0]
                                    dtindex = np.where(
                                        np.abs(dtArray[:, i]) <= maxDt)[0]
    
                                    index = np.intersect1d(cohindex, errindex)
                                    index = np.intersect1d(index, dtindex)
    
                                    wavg, wstd = wavg_wstd(
                                        dtArray[:, i][index],
                                        errArray[:, i][index])
                                    new_dtArray[i] = wavg
                                    new_errArray[i] = wstd
                                    new_cohArray[i] = 1.0
    
                            dtArray = np.vstack((dtArray, new_dtArray))
                            errArray = np.vstack((errArray, new_errArray))
                            cohArray = np.vstack((cohArray, new_cohArray))
                            pairArray.append("ALL")
                            del new_cohArray, new_dtArray, new_errArray,\
                                cohindex,errindex, dtindex, wavg, wstd
```
seems like maybe there needs to be a catch for when "tArray" is empty (? not sure how this happens) but that's about as far as my expertise goes. any short-term workarounds appreciated assuming not addressed in a later edition

**Comment by ThomasLecocq** [comment]
yep, tArray is empty, which should not occur. How did you define the maxlag and dtt_* parameters ?

**Comment by filefolder** [comment]
ah the problem appears to be that my MWCS output (.txt) data were all empty files. i'd guess the input filter settings were too large or otherwise wrong and/or possibly due to my not setting "rms threshold" to a value. 

fwiw after some review have adjusted to:

low 0.01
mcws low 0.03
mwcs hi 7.9
hi 8.0 hz, with wlen = 10 & step = 5, and rms now explicitly set to 0.0. with default settings for everything else. 

still reprocessing but i suspect that may still be too wide a filter band. regardless at this point the problem seems to be more science than software and definitely on my end, so closing. cheers

**Comment by ThomasLecocq** [comment]
Hey, good you found out. I really need to kill that rms_threshold in the next version.
