### ISSUE TITLE
No NN,EE,ZE,ZN computed during the cross-correlation jobs

### ISSUE THREAD

**Issue by Corentin3** [ROBelgium/MSNoise#155]
When running compute_cc with ZZ,NN,EE,EN,ZE,ZN set in the components_to_compute_single_station field, and also in components_to_compute, nothing is computed for NN,EE,EN,ZE,ZN

**Comment by ashtonflinders** [comment]
Related to;
#121

**Comment by ThomasLecocq** [comment]
is this solved now @Corentin3 

does it relate to https://github.com/ROBelgium/MSNoise/issues/153 ?
