### ISSUE TITLE
Improve Database creation

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#18]
Improvement:
- What to do if already exists ?
- Provide a Deleter ?
- Etc

**Comment by ThomasLecocq** [comment]
not needed to release 1.3, moving to 1.4

**Comment by ThomasLecocq** [comment]
moving to 1.5

**Comment by rantanplan77** [comment]
add a table prefix that can be empty to ensure backwards compatability

**Comment by ThomasLecocq** [comment]
> add a table prefix that can be empty to ensure backwards compatability

done

**Comment by ThomasLecocq** [comment]
> Should also find a way to dump/import the db for copying/pasting projects

done and it was the most important...

``msnoise db execute "SQL QUERY" `` allows expert users to interact with the database (!CAUTION!)
