### ISSUE TITLE
how to import file in this software either from terminal or using Mysql also, which format of  data will be required?  please help in detail

### ISSUE THREAD

**Issue by Shiv-Mangal** [ROBelgium/MSNoise#180]

**Comment by ThomasLecocq** [comment]
Dear @Shiv-Mangal 

Welcome to MSNoise.

To start, I suppose you have read the documentation and the description of the Workflow:

http://msnoise.org/doc/workflow/0000_intro.html

Where all steps are explained with details.

In brief, you data has to be readable by ObsPy, see : https://docs.obspy.org/packages/autogen/obspy.core.stream.read.html --> Supported Formats

and then, if they are not arranged in a known data folder structure (SDS, BUDS, etc), then you can use the "Lazy mode" by forcing the ``scan_archive`` step to scan a specific folder and try to read all the files it contains.

For such questions, it is also better to ask the Mailing List, as this is not "an issue".

Have fun with MSNoise!

Thomas
