### ISSUE TITLE
sp.signal.hilbert(c) in api.py 

### ISSUE THREAD

**Issue by iceseismic** [ROBelgium/MSNoise#188]
Hi,  
when forming an interferogram using "get_results",  and using format="stack",  (with stack_method = "pws" )  I hit a problem inside msnoise/api.py  line 1261 in stack,  with the line  
      phase = np.angle(sp,signal.hilbert(c)) 

The runtime Error message was:
AttributeError:  module 'scipy' has no attribute 'signal'

I got past the error by  placing "import scipy.signal" up at the top of api.py

**Comment by ThomasLecocq** [comment]
should be fixed with https://github.com/ROBelgium/MSNoise/issues/188
