### ISSUE TITLE
Tomo plugin install Error

### ISSUE THREAD

**Issue by NimaDolatabadi** [ROBelgium/MSNoise#191]
I'm going through the instruction in here [http://msnoise.org/plugins/msnoise-tomo/doc/#installation-adding-the-plugin-to-a-project](msnoise-tomo) but when I do `msnoise p tomo install` this gave me the following error:

> Usage: msnoise p [OPTIONS] COMMAND [ARGS]...
> Try "msnoise p --help" for help.
> 
> Error: No such command "tomo".

while this command `msnoise config set plugins=msnoise_tomo` gave me this output: `Successfully updated parameter plugins = msnoise_tomo`

Please help me on this issue.
Regards.

**Comment by ThomasLecocq** [comment]
It seems you didn't install the msnoise-tomo python package, which then makes it not available as a plugin. you need to install it first: download and pip install it from https://github.com/ThomasLecocq/msnoise-tomo
