### ISSUE TITLE
Is Windsorizing actually Winsorizing (without d)? 

### ISSUE THREAD

**Issue by omrivolk** [ROBelgium/MSNoise#192]
See https://en.wikipedia.org/wiki/Winsorizing

**Comment by ThomasLecocq** [comment]
it is... changing this now would require changing the paramter name in the database. I think it's best if I do this for MSNoise 2.0, when users have to upgrade their database.

**Comment by omrivolk** [comment]
Yeah, good idea. Just wanted to make sure I know what it's doing. Thanks
