### ISSUE TITLE
scipy functions deprecation

### ISSUE THREAD

**Issue by nikosT** [ROBelgium/MSNoise#194]
The scipy.fftpack._fftpack module doesn't exist in scipy version > 0.14.1
`
  File "/home/sysadmin/anaconda3/envs/msnoise/lib/python3.6/site-packages/msnoise/api.py", line 29, in <module>
    import scipy.fftpack._fftpack as sff
ModuleNotFoundError: No module named 'scipy.fftpack._fftpack'
`

**Comment by ThomasLecocq** [comment]
euh ? 0.14.1 ??

![image](https://user-images.githubusercontent.com/916937/72527876-046a8500-386a-11ea-88a8-aa0a1d200d9a.png)

**Comment by nikosT** [comment]
After the 0.14.1 version of the scipy package, the scipy.fftpack._fftpack module, doesn't exist. It only exists at scipy versions earlier than 0.15.0.

**Comment by ThomasLecocq** [comment]
Well, it works on my machine with:
```python
In [1]: import scipy.fftpack._fftpack as sff

In [2]: sff
Out[2]: <module 'scipy.fftpack._fftpack' from 'C:\\ProgramData\\Anaconda3\\envs\\py37\\lib\\site-packages\\scipy\\fftpack\\_fftpack.cp37-win_amd64.pyd'>

In [3]: import scipy

In [4]: scipy.__version__
Out[4]: '1.3.0'
```

**Comment by nikosT** [comment]
I confirm that runs with 1.3.0 version of scipy. However, it doesn't with version 1.4
Btw, msnoise v1.6, needs to modify the __version__ variable from 1.3 to 1.6

**Comment by ThomasLecocq** [comment]
I'm lost? 0.14.1 vs 1.4?

**Comment by nikosT** [comment]
if scipy == 1.4:
I get the module not found error.
else:
OK

PS: I thought that 0.14.1 was the last version that supported this module. However, 1.3 also support it.

**Comment by ThomasLecocq** [comment]
OK thank you for reporting. While you're at it with #195, please make sure to support both pre and post 1.4.0 while keeping the functionality of the cache cleaning.
Thanks

**Comment by ThomasLecocq** [comment]
should be solved with https://github.com/ROBelgium/MSNoise/pull/197
