### ISSUE TITLE
Removing instrument response with resp files

### ISSUE THREAD

**Issue by ChiouTingTan** [ROBelgium/MSNoise#202]
In the config page, the choices for response format includes resp files, but in actual fact, we can't use resp file format for instrument removal. Would be great if resp file formats can be used.

**Comment by ThomasLecocq** [comment]
Thanks for reporting this here, it helps keeping track.

This should be solved now with https://github.com/ROBelgium/MSNoise/commit/e1de12bc690661546413c06be59fc3c10f12d28e that eventually will lead to removing the ``response_fomat`` config, as *anything* that can be read using obspy will be allowed.

That part https://github.com/ROBelgium/MSNoise/commit/11c725fb44b6a7930aa5ba3b31afb032e58ffc39 of the documentation will also be added to help users check their response file is OK.
