### ISSUE TITLE
Msnoise INSTALLATION PROBLEM: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' (timed out)")

### ISSUE THREAD

**Issue by Lukman-abdn19** [ROBelgium/MSNoise#205]
Hi, I am trying to install Msnoise on a Mac (High Seirra)

The Anaconda3 I downloaded and installed works only when I have (base) at the left hand side of my terminal. All the msnoise installation steps works but gave me this message below when I try the msnoise bugreport;

(base) lukman$ msnoise bugreport
CRITICAL:root:Unable to read project configuration: error connecting to the database:
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' (timed out)")
(Background on this error at: http://sqlalche.me/e/e3q8)

I will very happy to get a suggestion on the way out of this problem

**Comment by ThomasLecocq** [comment]
please use gitter or the mailing list for questions.

The error is most probably because you did not follow the workflow (msnoise db init etc...)

**Comment by Lukman-abdn19** [comment]
Thanks,

Sorry I am not use to the platform, do you mean sending a mail (use mailing list)? And for the gitter, I don't know how to use it that is reason.

________________________________
