### ISSUE TITLE
some problems when initialize the database

### ISSUE THREAD

**Issue by promise-yy** [ROBelgium/MSNoise#206]
When I used 'msnoise db init' script, I made a mistake with the name of database in Mysql, so it always hints as:
F:\>msnoise db init
CRITICAL:root:Unable to read project configuration: error connecting to the database:
(pymysql.err.OperationalError) (1049, "Unknown database 'msnoise'")
(Background on this error at: http://sqlalche.me/e/e3q8)
I don't know how to reset the database name, please help me ,thanks!

**Comment by ThomasLecocq** [comment]
you can delete the db.ini file and re-do the `msnoise db init` command to create a correct version.
