### ISSUE TITLE
[question] dv/v plot from msnoise.move2obspy.mwcs

### ISSUE THREAD

**Issue by viictorjs** [ROBelgium/MSNoise#215]
Hello,

I'm using the msnoise.move2obspy.mwcs function and I'ld like to use the returned values for a dv/v plot.

Is there any specific msnoise function that I could use for this purpose within my python code?

Best regards

**Comment by ThomasLecocq** [comment]
Hi, 

Please use the mailing list or gitter for questions.

No, mwcs returns the dt for each time lag. You'll have to apply the compute dtt step for computing the linear regression through them, and that returns the dt/t.

**Comment by viictorjs** [comment]
Ok! Thank you @ThomasLecocq for the quick reply.
