### ISSUE TITLE
Failed msnoise tests with recent sqlalchemy version

### ISSUE THREAD

**Issue by asyates** [ROBelgium/MSNoise#217]
Recently encountered issue where, on creating a new environment in conda, installing msnoise, and running 'msnoise test', I was getting errors like those attached in the test.log (4 of the 52). These are from someone else, but I was able to reproduce the errors following the same process (i.e. installing msnoise inside a new conda environment). Outside of the conda environment, the same version of msnoise ran the tests with no problems.

In the end, I was able to fix it by downgrading the module sqlalchemy, installed during obspy install, to an earlier version. So running:

conda install -c conda-forge sqlalchemy=1.3.13

Not sure on the specifics as to why exactly it is failing with the newer version of sqlalchemy.

[bugreport.log](https://github.com/ROBelgium/MSNoise/files/6173240/bugreport.log)
[test.log](https://github.com/ROBelgium/MSNoise/files/6173241/test.log)

**Comment by ThomasLecocq** [comment]
looks like it's related to this:

> sqlalchemy.exc.ArgumentError: Textual column expression 'day' should be explicitly declared with text('day'), or use column('day') for more specificity

will investigate

**Comment by ThomasLecocq** [comment]
It's that... 
will require _some_ work....

**Comment by ThomasLecocq** [comment]
hopefully solved by https://github.com/ROBelgium/MSNoise/commit/fa18e3df1a7a19271a24ba92154edf1bda4b16ce - waiting for CI

**Comment by ThomasLecocq** [comment]
🟢 works!!
