### ISSUE TITLE
stretch.py expecting old file naming structure

### ISSUE THREAD

**Issue by asyates** [ROBelgium/MSNoise#220]
Minor issue, stretch.py currently searches for MSEED files using old naming structure ('_' between network, station code, and location). So will always fail to find the reference stacks.

Easily fixed just making the change on line 105 of stretch.py:

```ref_name = pair.replace('.', '_' ).replace(':',  '_')```

to 

```ref_name = pair.replace(':', '_')```

**Comment by ThomasLecocq** [comment]
aha, indeed, didn't check that part of the code. Please PR the changes. And also check the work from Jannik on the plotting of stretching results

**Comment by asyates** [comment]
Will do, think I've just about sussed out the process ;) (i.e. forking and pull requests). 

Forking the most recent version of MSNoise, I also realised that there are other changes related to updates to the .apy file. Will include these fixes too.
