### ISSUE TITLE
Storage question

### ISSUE THREAD

**Issue by aanader** [ROBelgium/MSNoise#224]
Hello,
I am using MSNoise on a computing center "mésocentre" that I can acess remotely through NOMachine. 
I Use two main spaces: archive (for data storage) and user1 where I do all the computing and where I have storage limitation (about 5 Gbs). Usually, my MSNoise database is saved in my user1 space since it's there where I set the command lines, along with all the folders obtained during the CC processing. 
Is there a way to save my database and the corresponding folders in the archive space while doing all the computation in the user1 space?

Thank you,
Anthony Abi Nader

**Comment by ThomasLecocq** [comment]
Hello Anthony,

If storage on `user1` is limited and you fear it will not hold the database (usually small, except if your project is very large, with many stations) and the output data (especially if you use the `keep_all` option, which creates a lot of heavy HDF5 files) - then the best would be to move the whole project folder to the storage where you have enough quota, and run from there.

**Comment by aanader** [comment]
In fact the folder which contains the databse (DTT, STACKS and MWCS) is about 12 Gbs even though I am doing a single station autocorrelation (but on a 3 year-data).
I cannot run any computing on the storage space...

**Comment by ThomasLecocq** [comment]
but the storage is mounted on the processing machine ? otherwise I don't see how you could do it

**Comment by aanader** [comment]
Yes indeed, I was just checking if there is a way to change the directory in which are saved the DTT, STACKS and MWCS, instead of being saved automatically in the directory were the db is created.

**Comment by ThomasLecocq** [comment]
if you can write to the storage, why don't you just run the command in that folder ? I don't understand.
No, the db.ini, the sqlite file and the subfolders are in the same folder.
