### ISSUE TITLE
msnoise compute_cc CPU problem

### ISSUE THREAD

**Issue by sujan1746** [ROBelgium/MSNoise#228]
Hi, I am new to msnoise and I got a problem with CPU.

I am in a lab and share a limit capacity of CPU in a server.

However, when I run msnoise compute_cc (or msnoise -t number compute_cc), the percentage of CPU becomes  over 92.

So whenever I use the '-t' comments (threads), it needs too much cpu and makes others' operation slow.

Even though I saw parameters and changed them, nothing changed.

Thus, please let me know what I have to do to reduce the cpu share.

p.s.) I attach a screenshot of top when I run 'msnoise -t 4 compute_cc'. It is almost 90%.
CPU of per PID (sujan) is over 100% and others' cpu (mkim) is lower than 100% which was almost 100% before I run msnoise.
If I use over '-t 4', it becomes faster than before but load average becomes over 200 ( or sometimes over 1300 when use high number of threads). I want faster but low load average operation.
![image](https://user-images.githubusercontent.com/89066297/129683702-d0cb9672-b9ba-49aa-b540-24a50c8ec911.png)

**Comment by ThomasLecocq** [comment]
Hi,

It is common that the CPU value for python codes doesn't represent the real/actual usage. But, compute_cc is computing a LOT of operations that are CPU intensive, most of them being FFT/iFFT, so this is pretty normal.

`-t 4` is of course only recommended if you have multiple cores (real cores ideally, not hyperthreading) ; and so it makes sense it's taking more resources. I recommend using `htop` for viewing how the load is spread over cores.

**Comment by sujan1746** [comment]
Thank you for reply. 

I can see cpu value does not represent the real usage and a lot of operations of cpu is normal.

However, is there any way to reduce the cpu coverage?

Because I share a limit cpu capacity with others.. (if I use too much cpu, their works become too slow)

**Comment by ThomasLecocq** [comment]
Well, compute on one thread. But then, I mean, it's the goal of the code to use the resources available to do the computation (as fast as possible), so there are no "ways" to reduce it. FFT will always require CPU, etc...

**Comment by sujan1746** [comment]
I got it. Thank you for your help!
