### ISSUE TITLE
sampling rate

### ISSUE THREAD

**Issue by sujan1746** [ROBelgium/MSNoise#234]
Hi, I have to control sampling rate and I got the reply that I cannot control the sampling rate before.

But I still have to get the dvv data in **an hour data** (not 1 day data).

So I wonder is it possible to get the dvv data in an hour data or change sampling rate?

**Comment by ThomasLecocq** [comment]
I don't understand your question

**Comment by sujan1746** [comment]
I am sorry to make it unclear.

I mean, I want to get the dvv data (or plot) in an hour or second period.

When I get the data by processing, I can get data in one day period as I attach below.

![image](https://user-images.githubusercontent.com/89066297/135704150-4afe38f7-a6ab-40b4-8371-94892672aaa7.png)

So is it possible to modify codes to get dvv data in an hour or second period?
e.g. About a second period)
Date, A, EA, EM, EM0, M, M0
2013-09-29 00:00:00 A EA EM EM0 M M0
2013-09-29 00:00:01 A EA EM EM0 M M0
2013-09-29 00:00:02 A EA EM EM0 M M0

**Comment by ThomasLecocq** [comment]
No, not easily. MSNoise has built-in support to keep all windows computed (of ``corr_duration`` length) - but not yet the ability to use those to compute MWCS & DTT/DVV.

I've never seen "1 second" dv/v, except in very high frequency, acoustic, studies, out of curiosity, why do you need this?

**Comment by sujan1746** [comment]
Oh.. I see..

I need that to monitor and expect the groundwater change.

**Comment by ThomasLecocq** [comment]
dv/v for each day is the default in MSNoise.
dv/v for hours or smaller could arrive in MSNoise 2, depending if I have time to code it (I don't think so...)
dv/v for each second will not be possible with the current code, I believe, but it _could_, you'll have to check all steps (certainly all the tapering, smoothing, etc) that were written to handle multi-minute data. The first step is to run with:

* ``keep_all = Y``
* ``corr_duration = 1``

and check the resulting h5 file produced using this example http://msnoise.org/doc/auto_examples/plot_interferogram.html#sphx-glr-auto-examples-plot-interferogram-py but adapting it to make use of the ``get_results_all`` method from the API.

**Comment by ThomasLecocq** [comment]
I guess you'll be using very high frequency auto correlation ? even so, you expect your waves to sample the groundwater in less than 0.5s ?

**Comment by ThomasLecocq** [comment]
note, one way to have enough data & higher "output" CCF is to define e.g. ``corr_duration = 600``and ``overlap = 0.99``

**Comment by sujan1746** [comment]
I found it is limited to download groundwater data in hours data (Sorry for confusing)
So I need only hours data.
Then I can get CCF for hours in MSNoise and it is hard to get dv/v for hours yet.
For getting CCF for hours, does it still need corr_duration=600, overlap=0.99?

**Comment by ThomasLecocq** [comment]
At this stage, it's not possible to obtain hourly dv/v "built in" in MSNoise. I suggest you start with daily dv/v & compare with the daily averages/median.

No hourly CCF can be obtained using ``corr_duration = 3600` only.

**Comment by sujan1746** [comment]
I see. Thank you so much for your help!!
