### ISSUE TITLE
Stretching always erases previous results

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#236]
Why didn't anyone tell me....

Stretching does the "T"odo jobs, and erases the output CSV in the STR folder... So when computing STR for the whole archive, all is OK, then next day, the cron job will compute STR for 1 or 2 days, for example, and the csv will contain only those days...

**Comment by asyates** [comment]
Ah hadn't seen this! I guess because I am almost always working with old data (so not needing to add new data to existing data very often).

From the looks of it, you have fixed this now?

**Comment by ThomasLecocq** [comment]
I think so yes, but tbh that merge was a "******* I still have this open commit and I want to push the test stuff" , so highly untested!

**Comment by asyates** [comment]
Just to add, had no issues with the previous outputs being erased when have been processing real-time results recently! So appears to be okay (at least, without looking at the code for now).
