### ISSUE TITLE
Improving move2obpsy.whiten2 (when fft is zero leading to NaNs)

### ISSUE THREAD

**Issue by Alexnavi44** [ROBelgium/MSNoise#291]
The line 287 in move2obspy.py,  for the function whiten2 if whiten_type == 'HANN' should be:
fft[i] = np.divide(fft[i], np.abs(fft[i]), out=np.zeros_like(fft[i]), where=np.abs(fft[i])!=0)

instead of :
fft[i] /= np.abs(fft[i])

because sometimes the abs(fft) = 0 and Divide by zero produce Nans that are propagated all along and remove traces that are in fact good . By doing the correction i could have back more than 50% of the trace in a day

**Comment by ThomasLecocq** [comment]
Hey, thanks for this ! very interesting. so this means zeroes in the original fft will be zeros in the final too ? 
are you confortable to have the idea of proposing a PR for this ?

**Comment by Alexnavi44** [comment]
it means that when you normalize the fft by doing fft[i] /= np.abs(fft[i]), it results in NaNs when np.abs(fft[i]) = 0, and bad consequence of that it when you go back to time domain with signal.ifftn, the function does not want to deal with NaNs and gives a NaN trace.

**Comment by ThomasLecocq** [comment]
sorry for the delay, just did it now in https://github.com/ROBelgium/MSNoise/commit/e7cf4140a2363a12d19442cfd8587654c837cfe4
