### ISSUE TITLE
issue when populating data availability from SDS data structure

### ISSUE THREAD

**Issue by PeterMakus** [ROBelgium/MSNoise#305]
Hi,
I am trying to write a minimal msnoise example that reads data from an SDS data structure and, subsequently, computes some cross correlations. However, it seems as if msnoise is not able to find any of my files if I provide them in SDS structure, which, as I understand the documentation, should be possible/even the standard configuration of msnoise. My data structure looks like this:

```bash
.
├── data
│   ├── inventory
│   │   └── BE.MEM.xml
│   └── mseed
│       └── 2021
│           └── BE
│               └── MEM
│                   ├── HHE.D
│                   │   ├── BE.MEM..HHE.D.2021.152
│                   │   ├── ...
│                   ├── HHN.D
│                   │   ├── BE.MEM..HHN.D.2021.152
│                   │   ├── ...
│                   └── HHZ.D
│                       ├── BE.MEM..HHZ.D.2021.152
│                       ├── ...
├── db.ini
├── msnoise.sh
├── None
```

With cd into the folder above, I use the following commands to try and populate my database:

```bash
msnoise db init --tech=1
msnoise config set data_structure=SDS  # should be default?
msnoise config set data_folder=./data/mseed
msnoise config set response_path=./data/inventory
msnoise config set startdate=2021-06-01
msnoise config set enddate=2021-08-01
msnoise scan_archive --init --path ./data/mseed
msnoise populate --fromDA
msnoise db update_loc_chan
```

## Other things that could be relevant

My OS: ubuntu
how I installed MSNoise: over the version available over GitHub into a conda environment
MSNoise version: 1.6.1.post0+180.gb5ccbc8bfe.robelgium.master (according to conda list)

Let me know if there is something I am misunderstanding here.
Thanks for your time and your help!

Peter

**Comment by ThomasLecocq** [comment]
Hey Peter,

Since you are using the SDS structure, you don't have to provide the --path , it'll parse it automatically, but you have to do the populate first:

    msnoise populate
    msnoise scan_archiove --init

Alternatively, you have to use the --recursively arg:

    msnoise scan_archive --init --path ./path --recursively
    msnoise populate --fromDA

Thomas
