### ISSUE TITLE
msnoise stack -r

### ISSUE THREAD

**Issue by lhyxyw** [ROBelgium/MSNoise#310]
When I use the script  “msnoise stack -r”，the Terminal shows “AttributeError: 'NoneType' object has no attribute 'starttime'”.

    elif begin == "1970-01-01":
        start = session.query(DataAvailability).order_by(
            _**DataAvailability.starttime).first().starttime.date()**_
        end = datetime.datetime.strptime(end, '%Y-%m-%d').date()
The class "DataAvailability" has the var "starttime".I donnot know why it cannot work.

**Comment by ThomasLecocq** [comment]
this should not occur, does the data_availability table contain data?

**Comment by lhyxyw** [comment]
I have solved this problem.Thank you ,sir!
