### ISSUE TITLE
problem about config

### ISSUE THREAD

**Issue by amell567** [ROBelgium/MSNoise#328]
Hello, I don't know why my msnoise was uninstalled today. After I re-installed, msnoise test could not take effect and the config interface showed an error. What should I do？
![YBWS8%7$CY_}{R2F SLAE_G](https://github.com/ROBelgium/MSNoise/assets/161307980/7478e91b-0a1e-4718-9d6f-608ae1377cde)
![90F`3T$4A%W{OK5SM9DNWR8](https://github.com/ROBelgium/MSNoise/assets/161307980/58c121e6-1f82-4d2e-8440-40255e0d5510)
![_C{KDVAW(FVAHI22ML 5`K0](https://github.com/ROBelgium/MSNoise/assets/161307980/89bac67b-bb52-4182-8b68-698987e4d8fe)

**Comment by amell567** [comment]
![90F`3T$4A%W{OK5SM9DNWR8](https://github.com/ROBelgium/MSNoise/assets/161307980/2f0e92fc-763d-4720-b58c-401e46008795)
![_C{KDVAW(FVAHI22ML 5`K0](https://github.com/ROBelgium/MSNoise/assets/161307980/780a817b-9a9a-4342-a11a-b14058235216)

**Comment by amell567** [comment]
![@ZX41RGNZ39T35QH LD$YKN](https://github.com/ROBelgium/MSNoise/assets/161307980/6a6fd9a3-eab8-4b80-82b6-82b68893f26e)

**Comment by ThomasLecocq** [comment]
I guess you reinstalled from "master", which is under development for the moment.

the ``windsorizing`` parameter was replaced by ``winsorizing`` , which you can adapt by:

``msnoise db execute "update config set name='winsorizing' where name='windsorizing' " `` 

please note that it's not the only change to the dev version, including the new mov_stack parameter structure etc.
