### ISSUE TITLE
the issue about c_c jobs

### ISSUE THREAD

**Issue by unluckyC** [ROBelgium/MSNoise#331]
hallo  dr.Thomas . I would like to inquire about an issue I encountered while working on a c_c—job. After completing the cc job, I noticed that it did not trigger the creation of the stack job. Additionally, when I attempted to use msnoise plot interferogram to output an image, the result was a blank image. (Note: I am still in the process of learning how to use msnoise, so I have only selected data from a few stations for my analysis. I have also tried using the UV-05, Uv-06, and Uv-10 data from the test set, but the outcome remains the same. Furthermore, I have modified all scripts of "scipy version <1.40" in the code to "scipy version <1.0.0" because I discovered that it was incorrectly identifying scipy 1.12 as being lower than scipy 1.4.0. I'm not sure if this could have any impact on the issue I'm experiencing.) 
Thank you very much for taking the time to answer my question.
![2024-03-12 021326](https://github.com/ROBelgium/MSNoise/assets/163023780/33cb0723-d194-4f92-9d6b-43afc5df0584)

**Comment by ThomasLecocq** [comment]
This refers to an old release version, closing.
