### ISSUE TITLE
Pandas 2.2.0 and SQL mismatch when importing a database

### ISSUE THREAD

**Issue by zibiwilczynski** [ROBelgium/MSNoise#351]
Hi, 

I discovered a mismatch between Pandas 2.2.0 and SQL used by msnoise when importing a database. I fixed it by downgrading pandas to 2.1.4 as suggested in [this thread](https://stackoverflow.com/questions/38332787/pandas-to-sql-to-sqlite-returns-engine-object-has-no-attribute-cursor).

**-- How to reproduce? --**

Using Pandas 2.2.0, run:

```
msnoise db dump
msnouse db import stations --force
```

**-- What is the error message? --**

`AttributeError: 'Engine' object has no attribute 'cursor'`

**-- How to fix it? --**
I downgraded my Pandas to 2.1.4. and it worked just fine.

```
conda install pandas=2.1.4.
msnoise db import stations --force
```

I hope that helps

**Comment by ThomasLecocq** [comment]
this should work now (still work to do for matching the types, but it should work for all sql engines): https://github.com/ROBelgium/MSNoise/commit/05365e6159cd765a769ca5094b7ace00a5fe56fc
