### ISSUE TITLE
MWCS plot error

### ISSUE THREAD

**Issue by BANadim** [ROBelgium/MSNoise#358]
Hello, 

Getting an error message when I try to plot for the MWCS, i tried different integer values for -m option and different station combination but to no avail. Please help! thank you.
![MWCS2](https://github.com/user-attachments/assets/adf7d4e0-7345-46c3-a485-007cdd2371e3)
![mwcs error](https://github.com/user-attachments/assets/5ca65fff-692b-4a6d-b425-3fd1c99e3057)

**Comment by ThomasLecocq** [comment]
are you using the release version of msnoise (1.6.3), installed with pip/conda ? If yes, it's already a pretty old version and there are maybe parts of the code that fail due to changes in the dependencies (pandas seem the culprit here).

You can also check if the MWCS data exist for this pair/day.
