### ISSUE TITLE
plot_distance_error

### ISSUE THREAD

**Issue by VishalsRawat** [ROBelgium/MSNoise#361]
Dear Sir, I am using msnoise, I got error in distance plot . After the cross-correlation when I run the command "msnoise plot distance" it calculates the interstation distance but does not get the result plot in matplotlib or waveform data is not showing and the same problem with data_availability when I run in the terminal but in the server, it shows plot when using GUI through admin command in the terminal.
Thank you for your time.

**Comment by ThomasLecocq** [comment]
It is probably because your server has no gui capability, or you didn't tunnel the X server through SSH. Does the plot work when passing the ``-o test.png`` to the commands? It should create a file
