### ISSUE TITLE
Issue with msnoise admin web page section Interferogram Plotter and Result Plotter

### ISSUE THREAD

**Issue by FrancescoSans** [ROBelgium/MSNoise#364]
Hi, after executing from the CLI  the how to steps we've tried to get interferogram plot from the admin web interface but the result is the one in the picture. No useful information from the log in the shell were we've launched msnoise admin command. Also the "Result  plotter section" is not usable due to an UnboundLocalError exception .  I've attached screenshosts.
We are using msnoise v. 2.0 in docker container with Ubuntu 24.04, but the same was with msnoise v. 1.6.2 . Plotting to output file with CLI command works well.
Thanks in advance for your help
024-09-09 11-34-21](https://github.com/user-attachments/assets/053db352-ee60-4574-93ba-b1268d46f9dc)
![Screenshot from 2024-09-09 11-39-17](https://github.com/user-attachments/assets/65967943-0b9f-46c9-9046-19e0f4d2c835)
![Screenshot from 2024-09-09 11-34-21](https://github.com/user-attachments/assets/37d668d2-d9a0-4573-87f4-8de5a94b5a59)

**Comment by ThomasLecocq** [comment]
Hi, the support for web plotting is not finalised, please use the command line.

**Comment by FrancescoSans** [comment]
Ok, thanks .
