### ISSUE TITLE
data_availability plot possible bug on MSNoise master

### ISSUE THREAD

**Issue by seismolab-uct** [ROBelgium/MSNoise#374]
Hi everyone,

I am working on a nodal dataset of 202 smart solo 3C stations. As suggested by @ThomasLecocq on #338 I have been working with the msnoise master.

The initial steps of scan_archive and populate fromDA worked well, it detected the ~17000 data files in the data folder and the 202 stations. I was able to generate a station map with the msnoise plot station_map command, however the data_availability plot does not seem to work.

I have tried a few different variations of the command (show, output to file, only vertical component, etc.) but no plot is generated or saved and no error is produced.
(msnoise) [seismolab@pocosol Tierra_Grande]$ msnoise plot data_availability
(msnoise) [seismolab@pocosol Tierra_Grande]$ 

I would appreciate any comments, maybe it is related to the number of files, or perhaps I am just missing something simple. Thanks for any help!

**Comment by ThomasLecocq** [comment]
What is the channel name? DPZ? In the data_availability table? This could be passed to the plot command (-h gives the options)

**Comment by seismolab-uct** [comment]
Hi @ThomasLecocq I tried the following:

```python
from msnoise.api import *
db = connect()
for sta in get_stations(db, all=True):
sta.used_location_codes = ""
sta.used_channel_names = "DP1,DP2,DPZ"
db.commit()
```
When I ran the ```msnoise new_jobs --init``` it didn't return an error but it inserted 0 Jobs. I checked the data availavility table and the Loc column had -- for every item, I then tried to modified the ```sta.used_location_codes = "--"``` 

I ran ```msnoise new_jobs --init``` again, but still inserted 0 Jobs. I would appreciate any suggestions, not sure what to try next, thank you.

![Screenshot from 2024-10-24 15-07-54](https://github.com/user-attachments/assets/1b28c996-5519-4f54-a736-f74c279232c5)

**Comment by ThomasLecocq** [comment]
What was the error of 

``msnoise db update_loc_chan`` 
?

This should parse the data and insert in the database for the corresponding station.

**Comment by seismolab-uct** [comment]
The full error output is attached as a text file, however here is the last bit which is an sqlalchemy.exc.OperationalError

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'msnoise_db.data_availability.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT data_availability.ref AS data_availability_ref, data_availability.net AS data_availability_net, data_availability.sta AS data_availability_sta, data_availability.loc AS data_availability_loc, data_availability.chan AS data_availability_chan, data_availability.path AS data_availability_path, data_availability.file AS data_availability_file, data_availability.starttime AS data_availability_starttime, data_availability.endtime AS data_availability_endtime, data_availability.data_duration AS data_availability_data_duration, data_availability.gaps_duration AS data_availability_gaps_duration, data_availability.samplerate AS data_availability_samplerate, data_availability.flag AS data_availability_flag 
FROM data_availability 
WHERE net=%(net)s AND sta=%(sta)s GROUP BY data_availability.net, data_availability.sta, data_availability.loc, data_availability.chan]
[parameters: {'net': 'XW', 'sta': '10001'}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```



[msnoise_db_update_loc_chan_error.txt](https://github.com/user-attachments/files/17518052/msnoise_db_update_loc_chan_error.txt)

**Comment by ThomasLecocq** [comment]
Hummm, thought that error had been corrected, what database engine are you using (sqlite/mariadb/postgresql)?

**Comment by seismolab-uct** [comment]
I did the installation with mysql and mysql workbench, I am checking if I correctly setup

```
[mysqld]
character-set-server=utf8
collation-server=utf8_unicode_ci
sql_mode="TRADITIONAL,NO_AUTO_CREATE_USER"
```

**Comment by seismolab-uct** [comment]
I checked the config file (I am using AlmaLinux 9) and it did not have the suggested fix, after adding the fix and attempting to restart mysqld failed, I found a suggestion online that mentioned changing [mysqld] for [mysql] and the restart of mysqld went fine, my.cnf file is below:
```
[mysql]
character-set-server=utf8
collation-server=utf8_unicode_ci
sql_mode="TRADITIONAL,NO_AUTO_CREATE_USER"
#
# This group is read both both by the client and the server
# use it for options that affect everything
#
[client-server]

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d
```

I re-started my project, created a new empty database, ran ```msnoise scan_archive --path ./Mseed_Data --recursively --init ``` which went fine, and then ran ```msnoise populate --fromDA``` and although it added all the 202 stations as in the figure below

![Screenshot from 2024-10-25 15-31-49](https://github.com/user-attachments/assets/150d0791-a4a1-4eed-9999-d03cbf3cee30)

The command returns an error at the end (full error attached) which occurs when the script is checking available loc ids and chans:
```
pymysql.err.OperationalError: (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'msnoise_db.data_availability.ref' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
```
My guess is that the sql_mode setting I am defining in my.conf is not being passed for some reason, maybe the usage of [mysql] but otherwise with [mysqld] at the beginning of the my.cnf file I can't even restart mysqld with ```systemctl restart mysqld```. 

I am going to try to permanently disable only_full_group_by and see what happens.

[msnoise_populate_fromDA_error.txt](https://github.com/user-attachments/files/17523316/msnoise_populate_fromDA_error.txt)

**Comment by seismolab-uct** [comment]
I tried to manually set the sql_mode, but when entering ```mysql -u root -p``` it returned errors of ```mysql: unknown variable 'character-set-server=utf8'``` after removing the corresponding line from my.cnf it returned similar errors for ```collation-server=utf8_unicode_ci``` and for ```sql_mode="TRADITIONAL,NO_AUTO_CREATE_USER"```.

I reverted back to removing all those variables from my.cnf and I was able to edit the sql_mode with
```mysql > SET PERSIST sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));```

I then ran ```msnoise populate --fromDA``` and this time it worked and it didn't return any errors and it has now added the loc ids and channels.

```
2024-10-25 15:28:57.690324 msnoise [INFO]: XW.50033 has locids:['--'] and chans:['DP2', 'DPZ', 'DP1']
2024-10-25 15:28:57.697164 msnoise [INFO]: XW.50034 has locids:['--'] and chans:['DP2', 'DPZ', 'DP1']
2024-10-25 15:28:57.703918 msnoise [INFO]: XW.50035 has locids:['--'] and chans:['DP2', 'DPZ', 'DP1']
2024-10-25 15:28:57.710552 msnoise [INFO]: XW.60000 has locids:['--'] and chans:['DP2', 'DPZ', 'DP1']
```

And everything looks good

![Screenshot from 2024-10-25 17-42-41](https://github.com/user-attachments/assets/66136241-4610-48b1-a991-29e4ebac3d2b)

Thanks for your time and suggestions @ThomasLecocq, maybe this will help other people using a RedHat derivative.

**Comment by seismolab-uct** [comment]
Going back to the original question, this sorts the data_availability plot
