### ISSUE TITLE
msnoise config sync possible issue

### ISSUE THREAD

**Issue by seismolab-uct** [ROBelgium/MSNoise#375]
After running ```msnoise config sync``` using an inventory file it populates the station table X, Y, Altitude, and Coordinates columns as expected, but I think the X and Y are flipped with respect to what the command ```msnoise plot station_map``` expects. 

In the screenshot below X was populated with latitude and Y was populated with longitude.

![Screenshot from 2024-10-25 18-13-05](https://github.com/user-attachments/assets/b2543305-28a6-4646-aafb-2937b55c5fd9)

Running ```msnoise plot sation_map -s True``` results in

```
 raise ValueError('%s must be between %f and %f degrees' %
ValueError: llcrnrlat must be between -90.000000 and 90.000000 degrees
```

Making X column the longitude and the Y the latitude
```python
from obspy import read_inventory
from msnoise.api import *
db = connect()
inv = read_inventory("Inventory/*.xml")
for sta in get_stations(db, all=True):
     sta_code = sta.sta
     stn = inv.select(station=sta_code)[0][0]
     sta.X = stn.longitude
     sta.Y = stn.latitude
     db.commit()
```
![Screenshot from 2024-10-25 18-20-35](https://github.com/user-attachments/assets/528d164c-9830-49cd-932f-d23c3d140bca)

Seems to resolve it
![Screenshot from 2024-10-25 18-26-43](https://github.com/user-attachments/assets/7c58003a-483f-4718-98d2-5678007a4c05)

**Comment by ThomasLecocq** [comment]
Humm that's strange, it should indeed be the default behaviour in msnoise.scripts.msnoise

**Comment by seismolab-uct** [comment]
I checked the lat and lon values for stations in the inventory file and plotted it in a local projection with obspy and looks fine, not sure if that helps but here is a screenshot
![Screenshot from 2024-10-25 18-43-57](https://github.com/user-attachments/assets/ff003610-4e04-4571-9116-673d5ebca112)

**Comment by ThomasLecocq** [comment]
Indeed , this seems wrong:

        update_station(db, station.net, station.sta, lat, lon, elevation, "DEG", )


Will investigate

**Comment by ThomasLecocq** [comment]
there was indeed a bug introduced last July (my mistake) - thanks for finding out!

It's now corrected with https://github.com/ROBelgium/MSNoise/commit/e8f6ad79960241ae046b580625f641aab7ec778a !
