### ISSUE TITLE
Report a small bug in the interferogram plot

### ISSUE THREAD

**Issue by chanewthon** [ROBelgium/MSNoise#386]
Hi,
I found that the refilter in the interferogram plot does not call the data correctly.
https://github.com/ROBelgium/MSNoise/blob/ec5e555f96b75a44114474507350248e88826d79/msnoise/plots/interferogram.py#L72-L74

I just fix it to 

            for i in range(len(data)):
                    data.iloc[i] = bandpass(data.iloc[i], freqmin, freqmax, cc_sampling_rate, zerophase=True)

**Comment by ThomasLecocq** [comment]
thanks for reporting, indeed that's pandas change that I forgot to correct. It'd be better to make use of ``.apply`` but for now your fix will do the job

**Comment by ThomasLecocq** [comment]
should be fixed in https://github.com/ROBelgium/MSNoise/commit/ffd3c7e4c528f4a06f4f7aae6d5fc7b1e1eb68a9 , please reopen if that's not the case! Thanks again
