### ISSUE TITLE
msnoise2.0 cannot be installed

### ISSUE THREAD

**Issue by cheshire2cat** [ROBelgium/MSNoise#388]
Hello, I have a 2.0 installation problem.
I created a new environment with the conda command. I use "pip install http://msnoise.org/master.zip command mentioned in the documentation", but I can't use the 2.0 commands cc and utils.The options for web page configuration are also the same as 1.6, as you can see from the pictures I took a screenshot, the last three configuration options in this undoubtedly indicate that they are version 1.6.

![6](https://github.com/user-attachments/assets/b0d42fcb-672e-4899-8de2-4ec9bcf0d60a)
![image](https://github.com/user-attachments/assets/d14b21d3-c34c-44a0-9bd3-dc0937d666fd)
![image](https://github.com/user-attachments/assets/1d6af4ef-caf0-49e6-ad3d-6cd942bbfa71)

**Comment by ThomasLecocq** [comment]
You have to remove the old code first:

``pip uninstall msnoise`` (maybe redo this command a few times)
then ``pip install http://msnoise.org/master.zip``

**Comment by ThomasLecocq** [comment]
please reopen if that didn't work, cheers
