### ISSUE TITLE
scan_archive, mtime, and data overlap

### ISSUE THREAD

**Issue by geopgirl09** [ROBelgium/MSNoise#40]
scan_archive changes files in data_availability table to 'M' even if they haven't changed (if they fall within the time range identified by 'mtime'.) This is apparently related to the date precision when Python reads the metadata and compares to the starttime and endtime columns in MySQL.

**Comment by ThomasLecocq** [comment]
@geopgirl09 : can you tell me if this happens with MySQL or SQLite ? or both ? I suspect it's only when using MySQL ?

**Comment by ThomasLecocq** [comment]
I know it's quite a major issue, but it could be moved to 1.3.x "bugfix" ? what do you think @geopgirl09  ?

**Comment by geopgirl09** [comment]
I was using MySQL. I think that sounds fine - I can work around it in the meantime.

**Comment by ThomasLecocq** [comment]
I've an idea, dropping microseconds from the start & endtime before saving/checking for modifications should do the trick... to test !
```python
starttime = starttime.replace(microsecond=0)
endtime = endtime.replace(microsecond=0)
```

**Comment by ThomasLecocq** [comment]
```python
In [3]: dt = datetime.datetime.now()

In [4]: dt.microsecond
Out[4]: 294000

In [6]: print dt
2015-03-17 08:48:12.294000

In [7]: dt = dt.replace(microsecond=0)

In [8]: print dt
2015-03-17 08:48:12
```

looks good :-)

**Comment by ThomasLecocq** [comment]
@geopgirl09 this cmmit should correct the bug, could you give it a try ?
