### ISSUE TITLE
Add interstation distance to SAC export

### ISSUE THREAD

**Issue by carmelosammarco** [ROBelgium/MSNoise#42]
This issue presents a tiny change in the add_corr methods, which pass the stations in order to later be able to add the distance in the SAC headers:

```python
 # Add stations s1, s2 for keep_all :
add_corr(s1, s2, db, station1.replace('.', '_'), station2.replace('.', '_'), 
               filterid, thisdate, thistime, min30 / fe, components, corr, fe)

 # Add stations s1, s2 for keep_days :
add_corr(s1, s2,  db, station1.replace('.', '_'), station2.replace('.', '_'), filterid,
               thisdate, thistime, min30 / fe, components, corr, fe, day=True, ncorr=ncorr)

```
in database tools, edit:

```python
def add_corr(s1, s2, db, station1, station2, filterid, date, time, duration, components, CF, sampling_rate, day=False, ncorr=0):
    ...
     if sac:
          export_sac(s1, s2, db, path, pair, components, filterid, CF/ncorr, ncorr)
```

the export_sac too:

```python
def export_sac(s1, s2, db, filename, pair, components, filterid, corr, ncorr=0, sac_format=None, maxlag=None, cc_sampling_rate=None):
    ....
    dist, azim, bazim = gps2DistAzimuth(s1.Y, s1.X, s2.Y, s2.X)
    ....
    tr.SetHvalue('DIST', dist)
    tr.SetHvalue('AZ', azim)
    tr.SetHvalue('BAZ', bazim)
```

**Comment by ThomasLecocq** [comment]
@carmelosammarco : i've edited the issue so you see how this could be done. The ideal case now would be that you fork MSNoise, you create a new branch in your repository, add this distance-in-sac-header feature on your machine, test it, then push to github, then finally prepare a pull request. This would automatically do what I've done above: show parts of the files that have been modified !

**Comment by ThomasLecocq** [comment]
by the way, are DIST, AZ and BAZ allowed keywords in the sac headers ? if yes, is the type OK ? float ? int ?

**Comment by carmelosammarco** [comment]
@ThomasLecocq  i forked Msnoise..now i am trying to figure out in witch way i can create a new branch in my repository... after i will do my modification and push on github.. and finally i will do a pull request. i hope that i will be able to do it.. :) i will ask you in case..

**Comment by carmelosammarco** [comment]
@ThomasLecocq   i forked Msnoise..now i am trying to figure out in witch way i can create a new branch in my repository... after i will do my modification and push on github.. and finally i will do a pull request. i hope that i will be able to do it.. :) i will ask you in case..

**Comment by ThomasLecocq** [comment]
Perfect! Good Luck !
