### ISSUE TITLE
traitsui dependency should be versioned

### ISSUE THREAD

**Issue by fcivilini** [ROBelgium/MSNoise#53]
Database setup utility (and possibly other gui apps) fails with a
segmentation fault when running under Ubuntu 12.04. Tracking this down
showed that it stems from exceptions occurring internally within
traitsui. I.e. this is not a msnoise issue per se. 

Replacing the system traisui (4.0) with upstream (4.5) resolves this
issue.

setup.py (line 17) should be updated so that the traitsui dependency is
versioned. I cannot determine if this behaviour is present with versions
4.1 to 4.4. So:

        traitsui>=4.5   will definitely work
        traitsui>4.0    might work

**Comment by ThomasLecocq** [comment]
travis looks happy with traitsui>=4.4 ... will implement it in the requirements

**Comment by ThomasLecocq** [comment]
done in https://github.com/ROBelgium/MSNoise/commit/a639b9022e208e4367b56558ac8a7f971166177f
