### ISSUE TITLE
Problem reading Sac files

### ISSUE THREAD

**Issue by echavess** [ROBelgium/MSNoise#59]
There's a problem when exporting/creating sac files during Cross-correlation:

msnoise compute_cc 
/Users/ech/github/obspy/obspy/__init__.py:150: ObsPyDeprecationWarning: Module 'obspy.sac' is deprecated and will stop working with the next ObsPy version. Please import module 'obspy.io.sac' instead. 
? ObsPyDeprecationWarning) 
/Users/ech/github/obspy/obspy/core/util/deprecation_helpers.py:55: ObsPyDeprecationWarning: Function 'obspy.core.util.gps2DistAzimuth' is deprecated and will stop working with the next ObsPy version. Please use 'obspy.geodetics.gps2dist_azimuth' instead. 
? ObsPyDeprecationWarning) 
2015-10-13 19:48:12 [INFO] *** Starting: Compute CC *** 
2015-10-13 19:48:12 [INFO] Will compute ZZ 
2015-10-13 19:48:12 [INFO] New CC Job: 2012-01-01 (1 pairs with 2 stations) 
2015-10-13 19:48:16 [INFO] Pre-Whitening Traces 
2015-10-13 19:48:16 [INFO] Processing CC 
Traceback (most recent call last): 
? File "/Users/ech/anaconda/bin/msnoise", line 9, in <module> 
? ? load_entry_point('msnoise==1.3', 'console_scripts', 'msnoise')() 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/scripts/msnoise.py", line 392, in run 
? ? cli(obj={}) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 610, in __call__ 
? ? return self.main(*args, **kwargs) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 590, in main 
? ? rv = self.invoke(ctx) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 936, in invoke 
? ? return _process_result(sub_ctx.command.invoke(sub_ctx)) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 782, in invoke 
? ? return ctx.invoke(self.callback, **ctx.params) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/click-3.3-py2.7.egg/click/core.py", line 416, in invoke 
? ? return callback(*args, **kwargs) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/scripts/msnoise.py", line 173, in compute_cc 
? ? main() 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/s03compute_cc.py", line 363, in main 
? ? thisdate, thistime, params.min30 / params.goal_sampling_rate, 'ZZ', daycorr, params.goal_sampling_rate, day=True, ncorr=ndaycorr) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/api.py", line 851, in add_corr 
? ? ncorr) 
? File "/Users/ech/anaconda/lib/python2.7/site-packages/msnoise-1.3-py2.7.egg/msnoise/api.py", line 891, in export_sac 
? ? tr = SacIO(filename) 
? File "/Users/ech/github/obspy/obspy/io/sac/sacio.py", line 298, in __init__ 
? ? self.read_sac_file(filen) 
? File "/Users/ech/github/obspy/obspy/io/sac/sacio.py", line 608, in read_sac_file 
? ? self.hf = from_buffer(fh.read(4 * 70), dtype=native_str('<f4')) 
AttributeError: 'str' object has no attribute 'read'

**Comment by ThomasLecocq** [comment]
fixed in https://github.com/ROBelgium/MSNoise/commit/0350486e92852bd242d01b7ffcca180ef8de2b58
