### ISSUE TITLE
Doc Addition for MySQL bug (group by)

### ISSUE THREAD

**Issue by ThomasLecocq** [ROBelgium/MSNoise#72]
add:
On Ubuntu 16.04 u need to add this at the end of my.cnf file:

[mysqld]
sql_mode="TRADITIONAL,NO_AUTO_CREATE_USER"

**Comment by rantanplan77** [comment]
On Mac it works as long as ONLY_FULL_GROUP_BY is deactivated. You can check this with this SQL-command: `SELECT @@sql_mode`

My /etc/mysql/my.cnf has these lines and it works:
`[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Note that you need to restart mysqld after these changes!

**Comment by rantanplan77** [comment]
A useful step-by-step guide to install MySQL on Mac is here: [https://coolestguidesontheplanet.com/get-apache-mysql-php-and-phpmyadmin-working-on-osx-10-11-el-capitan/](url)

**Comment by ThomasLecocq** [comment]
We'll get rid of phpMyAdmin and most probably of easyphp on windows, and suggest mysql-server and mysql-workbench for all platforms.

**Comment by ThomasLecocq** [comment]
doc updated. closing for now.

**Comment by Lukman-abdn19** [comment]
Hi, I am trying to install Msnoise on a Mac (High Seirra) 

The Anaconda3 I downloaded and installed works only when I have (base) at the left hand side of my terminal. All the msnoise installation steps works but gave me this message below when I try the msnoise bugreport;

(base)    lukman$ msnoise bugreport
CRITICAL:root:Unable to read project configuration: error connecting to the database:
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'None' (timed out)")
(Background on this error at: http://sqlalche.me/e/e3q8)

I will very happy to get a suggestion on the way out of this problem

**Comment by ThomasLecocq** [comment]
please ask this question on the mailing list or gitter, not on a closed issue
