### ISSUE TITLE
MWCS colormap bug

### ISSUE THREAD

**Issue by rantanplan77** [ROBelgium/MSNoise#79]
msnoise plot mwcs fails in Py3.5: 

>  File "msnoise/scripts/msnoise.py", line 569, in mwcs
    main(sta1, sta2, filterid, comp, mov_stack, show, outfile)
  File "msnoise/plots/mwcs.py", line 147, in main
    plt.imshow(alldt.T, extent=xextent,aspect="auto",interpolation='none',origin='lower',cmap=cmap_center_point_adjust(cm.seismic,crange,0))
  File "msnoise/plots/mwcs.py", line 68, in cmap_center_point_adjust
    abs(center - range[0]) / abs(range[1] - range[0]))
  File "msnoise/plots/mwcs.py", line 56, in cmap_center_adjust
    return cmap_powerlaw_adjust(cmap, a)
  File "msnoise/plots/mwcs.py", line 42, in cmap_powerlaw_adjust
    cdict[key].sort()
AttributeError: 'map' object has no attribute 'sort'

Removing the colormap works, so it has to do with the colormap creation

**Comment by rantanplan77** [comment]
#81

**Comment by ThomasLecocq** [comment]
#81 indeed solves this issue, closing.
