### ISSUE TITLE
Problem in compute_mwcs

### ISSUE THREAD

**Issue by toufikc** [ROBelgium/MSNoise#86]
Hello everyone,

I'm a student working with MSNoise and new user of Python.

I got this problem on some couples, when running on 'msnoise compute_mwcs' :

 ```
 _File /msnoise/s05compute_mwcs.py, line 136, in main
    cur, ref, f.mwcs_low, f.mwcs_high, goal_sampling_rate, -maxlag, f.mwcs_wlen, f.mwcs_step)
  File /msnoise/move2obspy.py, line 355, in mwcs
    m, em = linear_regression(v.flatten(), phi.flatten(), w.flatten())
  File /msnoise/api.py, line 1498, in linear_regression
    xtol=1e-20)
  File /scipy/optimize/minpack.py, line 680, in curve_fit
    raise RuntimeError("Optimal parameters not found: " + errmsg)
RuntimeError: Optimal parameters not found: gtol=0.000000 is too small, func(x) is orthogonal to the columns of   the Jacobian to machine precision._
```

So I look on the code and don't understand why calling on :
```
try:
    from obspy.signal.regression import linear_regression
except ImportError:
    from .api import linear_regression
```

Is linear_regression exist on obspy? Or it is just in development like this version?

**Comment by ThomasLecocq** [comment]
Hi,

It's indeed something linked to the master version of MSNoise. The `linear_regression` is not yet in obspy, but will be in the next version (1.1), which is due soon.

I'll add a try-except for this error in mwcs, we had it using statsmodels when it failed.

**Comment by ThomasLecocq** [comment]
does the problem occur again with the current master version ?

**Comment by toufikc** [comment]
No, it's ok.
Everything works now

**Comment by ThomasLecocq** [comment]
Perfect, enjoy!
