### ISSUE TITLE
Set station coordinates in database from metadata?

### ISSUE THREAD

**Issue by megies** [ROBelgium/MSNoise#91]
Is there an option (after `msnoise populate`) to set station coordinates in station table from station metadata (dataless, stationxml, ..)? We didn't see an option.. Probably that's a missing command that would be very helpful..?

**Comment by rantanplan77** [comment]
`msnoise config --sync `

will try to parse the dataless files for existing stations in the Station table and, if found, will input the coordinates. (http://msnoise.org/doc/master/releasenotes/msnoise-1.5.html )

**Comment by ThomasLecocq** [comment]
works best in master with the new pre-parser of the dataless & inventories...

**Comment by ThomasLecocq** [comment]
aha, yep... because elevation is not taken into account in msnoise (yet)

**Comment by megies** [comment]
Ok, there's some additions in #94, closing this one..
