### ISSUE TITLE
Set separate component combinations for auto correlation

### ISSUE THREAD

**Issue by megies** [ROBelgium/MSNoise#92]
It would be good to be able to specify different channel combinations for auto correlation jobs.. so basically add a config key `components_to_compute_autocorr` that can be set differently from `components_to_compute`.

**Comment by ThomasLecocq** [comment]
that would indeed avoid computing two times everything (NE and EN being equal, for example)...

**Comment by ThomasLecocq** [comment]
or more generally ``components_to_compute_singlestation`` ;

**Comment by ThomasLecocq** [comment]
well, actually, the code could also automatically remove the duplicates...

**Comment by megies** [comment]
Yeah.. it's not about dups though, for example for autocorrelation you might want to use ZN while you don't want it for cross-correlation.

**Comment by ThomasLecocq** [comment]
true, I see your point now.

**Comment by ThomasLecocq** [comment]
done in 1.6, ``components_to_compute`` and ``components_to_compute_single_station`` are a fact, my Liege.
