### ISSUE TITLE
startdate and enddate vulnerable for whitespaces

### ISSUE THREAD

**Issue by heavelock** [ROBelgium/MSNoise#98]
Hi!
I'm slowly starting to learn how to properly use MSNoise :)

First real bug I've stumbled upon is connected with validation of input data in config. The fields startdate and enddate are not stripped out of whitespaces. That allows to add for example leading/trailing space which will cause an exception when using compute_dtt, and to exact build_movstack_datelist() method. 

Simple .strip() before saving to database should save quite a lot of debugging effort in the future. 

If everything goes like planned, I will submit a PR with a bugfix in the afternoon.

**Comment by ThomasLecocq** [comment]
Yep, good idea.

**Comment by ThomasLecocq** [comment]
resolved in #138
